# Generated by Django 4.2.9 on 2024-02-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('key', models.CharField(max_length=20)),
                ('title', models.CharField(default='Pastebin', max_length=30)),
                ('author', models.CharField(default='Anonymous', max_length=20)),
                ('description', models.CharField(default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
